// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sfnklrjfusaufkogogli.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNmbmtscmpmdXNhdWZrb2dvZ2xpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE4MzE2NTgsImV4cCI6MjA1NzQwNzY1OH0.0FsGDiH2lLVHPTf56Ywm17nbtuBQg62lfp2cs5reTqo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);