// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://onlamqkvlfjhtvqexyzq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9ubGFtcWt2bGZqaHR2cWV4eXpxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA4NDI0NzQsImV4cCI6MjA2NjQxODQ3NH0.DP2VP-3ovDi6v1LO34ssOaT-jQaLIYQevMPyBxamDMw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);